### ISSUE TITLE
Pyscript this up for online use?

### ISSUE THREAD

**Issue by SnesLover22** [3kh0/python-projects#3]
think this could get working online with a little thing called pyscript?  https://anaconda.cloud/pyscript-python-in-the-browser

**Comment by 3kh0** [comment]
I can try

**Comment by SnesLover22** [comment]
noice, hows it going so far? Is it working?

**Comment by 3kh0** [comment]
If you are able to get this running and make a pull request, that would be great, but i will get to it

**Comment by SnesLover22** [comment]
ok quick question: What are the libraries used here? Is it poetry and selenium only?

**Comment by SnesLover22** [comment]
hey did you ever get to pyscripting this?

**Comment by 3kh0** [comment]
No, I do not know how to use pyscript right now, it might be possible, I do not really know. Running the browser on a docker container is more stable anyway

**Comment by SnesLover22** [comment]
fair point.
